version = 0.1

[default.deploy.parameters]
stack_name = "metricapi"
resolve_s3 = true
s3_prefix = "metricsapi"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

[default.global.parameters]
region = "us-east-1"
