version = 0.1

[default.deploy.parameters]
stack_name = "auth"
resolve_s3 = true
s3_prefix = "auth"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"

[default.global.parameters]
region = "us-east-1"
